yoimiya-kokomi/miao-plugin

- resources/meta/reliquaries/artis-mark.js
> 修正圣遗物计算的充能效率词条成长值

- models/Avatars.js
> #面板练度统计 兼容yunzaiV3国际服接口天赋数据

- models/MysApi.js
全是水无一点技术含量，这里有个另外的问题，就是获取单个天赋的时候会一直输出日志，喵佬你看看怎么处理优化一下
> 修正#深渊配对 提示ck未绑定问题

- models/profile-lib/DmgCalc.js
- resources/meta/character/早柚/calc.js
- resources/meta/character/枫原万叶/calc.js
- resources/meta/character/温迪/calc.js
- resources/meta/character/砂糖/calc.js
> 把扩散反应的伤害计算归到整体的计算中

- apps/profile.js
yunzaibot自带的face**#表情列表**会误触grouprank的**#最强列表**
> 修正#表情列表的指令误触

- components/Format.js
- config/cfg_default.js
- config/system/cfg_system.js
> 伤害数字分组可自定义

- resources/meta/character/艾尔海森/calc.js
> 更新艾尔海森伤害计算

- apps/profile/ProfileUtils.js
为 #原图 功能增加30s后自动撤回，以减缓消息内容被刷屏/自定义图中出现setu但不能撤回的问题
> 为 #原图 功能增加30s后自动撤回

- resources/meta/character/夜兰/artis.js
> 夜兰精通阈值降至80

- resources/meta/character/夜兰/calc_auto.js
> 修复莫娜一命，现在对蒸发E生效

- resources/meta/character/香菱/calc_auto.js
> 香菱伤害面板增加精通对比

- resources/meta/character/提纳里/calc.js
> 修复提纳里天赋（单人）

- resources/meta/artifact/artis-mark.js
- resources/meta/character/迪希雅/artis.js
- resources/meta/character/迪希雅/calc.js
- resources/meta/character/迪希雅/calc_auto.js
- resources/meta/weapon/claymore/calc.js
> 更新迪希雅组队与单人伤害，以及迪希雅评分

- resources/meta/character/妮露/calc.js
- resources/meta/character/妮露/calc_auto.js
- resources/meta/character/艾尔海森/calc.js
> 增加妮露蒸发伤害，妮露组队伤害，修复海哥小bug

- README.md
> Update Snap.Hutao & API acknowledgement.

- resources/meta/character/可莉/artis.js
- resources/meta/character/可莉/calc.js
- resources/meta/character/可莉/calc_auto.js
添加可莉总伤计算、修改可莉排行依据、修改可莉圣遗物评分判定依据
> 调整可莉面板计算规则

- resources/meta/character/可莉/artis.js
- resources/meta/character/可莉/calc.js
- resources/meta/character/可莉/calc_auto.js
具体是这个更改https://github.com/yoimiya-kokomi/miao-plugin/pull/517
这个更改报错了，所以修一下
> 修复可莉不开启组队/圣遗物低配时会产生的bug

- apps/character/AvatarCard.js
- apps/character/ImgUpload.js
- apps/profile/ProfileCommon.js
- apps/profile/ProfileUtils.js
- apps/wiki/CharWiki.js
- index.js
以支持完全移除 OICQ 的 go-cqhttp 版 Yunzai
https://github.com/TimeRainStarSky/Yunzai
> 修改 segment 导入

- apps/profile/ProfileRank.js
- models/ProfileArtis.js
- models/ProfileRank.js
- models/profile/ArtisMark.js
- resources/character/rank-profile-list.html
- resources/meta/artifact/meta.js
> 更新加权词条评分与双爆

- apps/character/AvatarCard.js
- apps/character/ImgUpload.js
- apps/profile/ProfileUtils.js
- apps/wiki/CharWiki.js
go-cqhttp 版 Yunzai 需要检测 file:// 并进行转换
> 发送文件 URL 加上 file://

- apps/profile/ProfileRank.js
TRSS-Yunzai 部分适配器无获取头像函数，部分适配器获取头像函数需要 await
> 优化 角色排行头像处理

- apps/profile/ProfileRank.js
> 排名获取头像失败，导致发图失败

- config/system/cfg_system.js
- config/system/profile_system.js
- models/player/AvocadoApi.js
- models/player/EnkaHSRApi.js
- models/player/Profile.js
补上了目前公开的两个不同来源的api（鳄梨和enka）；
目前面板切换只有原神支持，鉴于二者面板api来源不通增加了设置项，单列出了`#喵喵设置星铁面板服务x`；
> feat: 新增两个星铁面板api及星铁面板服务的设置项

- resources/wiki/today-material.less
> 修复每日材料3、2、1星武器背景不显示

- resources/meta-gs/character/荒泷一斗/calc.js
- resources/meta-gs/character/荒泷一斗/calc_auto.js
> fix: 荒泷一斗的伤害 mainAttr

- models/serv/api/EnkaApi.js
> EnkaApi.js的代理配置写错了,应该是HttpsProxyAgent.default

- resources/meta-gs/character/提纳里/calc_auto.js
> Fix: 提纳里改成计算钟离减抗

- apps/profile/ProfileRank.js
- models/ProfileRank.js
> FIx: Match character id with different regex rules

- apps/stat/RoleCombatSummary.js
现在幻想的数据展示应该是基于 has_detail_data 的来
@SmallK111407 @TimeRainStarSky
> Fix: has_detail_data

- apps/character/ImgUpload.js
- config/system/cfg_system.js
这个命令触发一次就容易传个几十张图片，但是转发消息又没法发那么多，后台一直提示风控报错。占资源占带宽，给个可以关闭的选项挺好的
> feat: 新增选项，仅不允许获取面板图列表

- models/RoleCombat.js
- resources/stat/role-summary.css
- resources/stat/role-summary.html
- resources/stat/role-summary.less
（大部分）解决 issue #789 
应该只欠一个角色展示了
* `data.detail.fight_statistic.max_defeat_avatar`
* `data.detail.fight_statistic.max_damage_avatar`
* `data.detail.fight_statistic.max_take_damage_avatar`
这种角色展示应该去做的话又要调 html 和 css，相信后人的智慧
> Fix: 幻想真境剧诗改版解析

- apps/profile.js
- apps/profile/ProfileStat.js
- models/RoleCombat.js
- package.json
- resources/stat/role-summary.css
- resources/stat/role-summary.html
- resources/stat/role-summary.less
数据来源：HomDGCat 数据库
用法：
* `#202410幻想角色列表`
包括：筛选角色属性、加入开幕角色、特邀角色
关联 issue #788
> 添加命令：`#202410幻想角色列表`

- apps/profile/ProfileStat.js
- config/help_default.js
- config/system/help_system.js
关联 issue：#788
* 用角色的元素作为第一关键字排序
* 在查询范围超限时提示范围
* 在查询合法时返回简要信息
> 修复命令 `#202410幻想角色列表`

- resources/meta-gs/artifact/artis-mark.js
> 新增玛薇卡、茜特菈莉、蓝砚的圣遗物评分规则

- apps/profile/ProfileChange.js
- apps/wiki/CharWiki.js
- models/Character.js
- models/ProfileDmg.js
- resources/meta-gs/character/旅行者/artis.js
- resources/meta-gs/weapon/sword/calc.js
perf: 支持主角元素切换
* `主角面板换岩元素`
fix: 不同元素主角meta缓存
> fix: 原神主角天赋仅可查看风元素

- models/serv/api/MysPanelData.js
> fix: 修复米游社更新面板无法获取天赋的问题

- apps/help/HelpTheme.js
> 增加描述文字阴影标签

- resources/meta-gs/character/伊法/calc.js
- resources/meta-gs/character/爱可菲/calc.js
> fix爱可菲、伊法伤害计算优化【by 其实雨很好】

- resources/meta-gs/character/alias.js
> 增加伊涅芙别称（机器人/机娘）
