yoimiya-kokomi/miao-plugin

apps/admin.js
Windows上是`Already up to date.`
但是跑到Linux上居然变成了`Already up-to-date.`
导致无法判断是否是最新版了，这里兼容一下。
=> 兼容linux系统的git已是最新提示

apps/character.js, components/Common.js, index.js
为了防止redis缓存无限增长，设置了1个小时的过期时间，这个时间如果感觉不合理可以改一下。
----
关于`miao-plugin/components/Common.js` 第21行的修改，
目的是为了获取消息发送后的返回值，但是因为改了公共方法，所以可能会对别的功能造成隐患…… 我在提交之前也都测试过了，目前没有发现别的问题。
云崽这边因为是判断只要返回有值就进入break，所以也能正常进入 break（除非e.reply会返回null……应该不会吧）。
所以这么修改应该是没有太大的问题了，如果喵佬觉得不可以这么改那我就可以改成callback的方式
------
操作示例如下：
=> 新增`#获取原图`指令，用于获取角色卡片的原图

components/models/Reliquaries2.js
`char.lvStat.detail['90']` 中数据均为 `String` 类型
=> 修正攻击词条评分中的类型错误

config/profile_default.js
ENKA官网地址已经从`enka.shinshin.moe`已经变为`enka.network`。
新增两个代理访问节点，整理节点URL，推荐优先使用官方地址进行访问。
如果需要使用代理，理论上【广州节点】`https://3.enka.microgg.cn` 和【上海节点】`https://4.enka.microgg.cn` 速度是最快的。
=> 新增两个备用代理节点

apps/help/theme.js
在`help.js`里指定了皮肤名称
实际运行时并未生效
修复后：
=> 修复喵喵帮助设置`theme`不生效

apps/character/ImgUpload.js
groupConfig中支持可配置除主人以外的角色上传图片，但在判定权限时先判断是否为主人，导致即使配置中可由主人以外的人添加图片，但是会在这一步return false
=> fix: non-owners cannot upload img

resources/meta/character/八重神子/calc_teamC0R1.js, resources/meta/character/八重神子/calc_teamC6R5.js, resources/meta/character/刻晴/calc_teamC0R1.js, resources/meta/character/刻晴/calc_teamC6R5.js, resources/meta/character/夜兰/calc_teamC0R1.js, resources/meta/character/夜兰/calc_teamC6R5.js, resources/meta/character/宵宫/calc_teamC0R1.js, resources/meta/character/宵宫/calc_teamC6R5.js, resources/meta/character/提纳里/calc_teamC0R1.js, resources/meta/character/提纳里/calc_teamC6R5.js, resources/meta/character/甘雨/calc_teamC0R1.js, resources/meta/character/甘雨/calc_teamC6R5.js, resources/meta/character/神里绫人/calc_teamC0R1.js, resources/meta/character/神里绫人/calc_teamC6R5.js, resources/meta/character/神里绫华/calc_teamC0R1.js, resources/meta/character/神里绫华/calc_teamC6R5.js, resources/meta/character/达达利亚/calc_teamC0R1.js, resources/meta/character/达达利亚/calc_teamC6R5.js, resources/meta/character/雷电将军/calc_teamC0R1.js, resources/meta/character/雷电将军/calc_teamC6R5.js, resources/meta/character/香菱/calc_teamC0R1.js, resources/meta/character/香菱/calc_teamC6R5.js
增加了两种不同氪度的队友伤害，0命精1与满命满精。
八重：雷八九温
刻晴：刻九万妲
夜兰：夜万 or 夜万莫香（增加连招伤害）
宵宫：宵夜万班（增加连招伤害）
提纳里：提纳万（增加连招伤害）
甘雨：甘鹤万班
绫人：绫夜万班
神里：神鹤万莫
雷神：雷九万班，雷九万八
香菱，公子：万达
=> add team dmg

resources/meta/character/八重神子/calc_auto.js, resources/meta/character/可莉/calc_auto.js, resources/meta/character/胡桃/calc_auto.js, resources/meta/character/荒泷一斗/calc_auto.js
编辑：增加了胡桃双水钟离、一五钟岩队、可莉三火的伤害计算。
------
原八重组队温三雷判断条件：
2-5命八重搭配6+5温迪，6命八重搭配0+1温迪，1命以下没有温迪（什么鬼
现在修正为：0-5命八重搭配0+1温迪，6命八重搭配6+5温迪。应该更接近实际状况吧…
=> 增加了胡桃、一斗、可莉的组队伤害计算，修复了八重组队计算的错误

config/system/profile_system.js
I changed the URL to the API. `__data.json` will not work anymore.
There's now also `enka.network/api/uid/${uid}/?info` (test at `https://dev.enka.network/api/uid/600001919/?info`), which will return *only* the player info, but not avatar info. If you need it, you can use it, it's very fast compared to full data request.
=> The API route has been updated.

resources/meta/character/流浪者/calc_auto.js, resources/meta/character/纳西妲/calc_auto.js, resources/meta/character/魈/calc_auto.js
三个组队伤害。
草神默认为提八草皇（海八草皇也差不多伤害）
魈为魈珐班
散兵为散珐夜班与散珐云班
=> 添加草神，魈，散兵组队伤害

resources/meta/artifact/calc.js, resources/meta/character/久岐忍/calc.js, resources/meta/character/八重神子/calc_auto.js, resources/meta/character/夜兰/calc_auto.js, resources/meta/character/神里绫华/artis.js, resources/meta/character/菲谢尔/calc.js, resources/meta/weapon/sword/calc.js
结算顺序更改：
海哥提纳里专武尽量靠后结算，保证吃到更多的来自攻击力的buff。
饰金最前计算，保证海哥天赋吃得到对应加成。
余响最后计算，保证吃到更多的来自攻击力的buff。
功能增加：
八重菲谢尔激化伤害增加
久岐忍添加超绽放伤害，微测试花园套（我没有）。
bug修复：
修复了神里评分的物伤杯bug，夜兰组队状态应为3色天赋。
=> 增加八重，菲谢尔激化伤害（八重为组队），久岐忍超绽放伤害，与武器圣遗物结算顺序

resources/meta/weapon/catalyst/calc.js
具体问题是：https://github.com/yoimiya-kokomi/miao-plugin/issues/561
修复以后发现原函数忘记给精炼等级了，会导致计算Nan，所以顺便加上了。个人测试没问题了。
=> 修复碧落之珑计算bug

models/ProfileRank.js
QQ频道的groupId格式类似qg_113458249547xxxxxxxx-9719xxx，
x为数字，修改正则表达式适配该格式
=> 解决QQ频道调用时无法输出排名的问题

models/ProfileRank.js
=> fix 修复 #更新排名 命令无法获取uid绑定信息

resources/meta/artifact/artis-mark.js
我的一个项目引用了这个文件，一些角色数据的缺失导致我的项目报错了……希望补上（这些value均来自对应角色的artis.js）
=> fix: 补充artis-mark.js中遗漏的角色

resources/meta-gs/artifact/artis-mark.js
那维莱特首次UP时候，芙宁娜还没实装。
那维莱特带行秋or夜兰还是太抽象了，根本触发不了这俩协同攻击。
所以那维莱特自己要堆点充能，圣遗物评分充能权重给到了 75。
芙宁娜实装后，那维莱特队友里，芙宁娜占比非常高。
故调整那维莱特，将充能权重从75降低至55（参考魈圣遗物评分，充能权重同样为55）。
=> 更新那维莱特的圣遗物评分，将充能权重从75降低至55。

resources/meta-gs/artifact/artis-mark.js
将神里绫华和克洛琳德的攻击权重，从 75 提升至 85 。
克洛琳德的精通权重，从 75 降至 30 。
托马的生命权重提高到 100，攻击、双暴三项权重降至 50，充能权重提高到 75。
首先，神里绫华单人Q伤害，攻击头的期望以微弱优势高于暴伤头。
在队伍里有申鹤（1命）的情况下，神里Q的总伤，经本人面板测试，暴伤头只比攻击头高出仅仅 1% 左右。
如果是2命神里，则攻击头和暴伤头的Q总伤期望，几乎持平。
**当然对于不同面板来说，数据肯定会存在差异。
但至少能说明一个问题——将神里绫华的攻击权重，和其它主C角色设置成同为 75，这点是不合理的。**
为了和其他角色作为区分，故将神里绫华的攻击权重，从 75 提升至 85。
关于克洛琳德激化，0命克洛琳德自身一轮总攻击倍率能达到四五千（包括元素爆发和天赋），她的攻击词条的收益接近绫华（高命克洛琳德更甚）。
克洛琳德自身没有精通转模，**圣遗物精通副词条带来的激化伤害加成对于总伤的收益，远远远远低于攻击词条**
若将攻击和精通权重同设置成 75，将会让其它玩家误以为克洛琳德可以带精通沙，显然这是不对的。
=> 更新神里绫华、克洛琳德、托马的圣遗物评分权重

resources/meta-gs/artifact/artis-mark.js
精1专武克洛琳德，雷伤杯+攻击头 > 雷伤杯+暴伤头 ≈ 攻击杯+暴伤头。如果是精5专武，显然是攻击杯毕业。 龙王毕业面板是水伤杯+生命头，龙王的生命权重都能给到 100 。
克洛琳德，精1专武攻击杯打平雷伤杯，精5专武攻击杯毕业。真的没有理由不给 100 权重。
艾尔海森无论是黎明神剑、裁叶萃光，还是哪怕 674 白值的雾切，精通沙伤害都是吊打攻击沙的。把艾尔海森攻击权重甚至成 75 并不合理，这里把艾尔海森攻击权重，调整成和纳西妲一样，都是 55 。
赛索斯的精通倍率更夸张，天赋和普攻自带，让他拥有全游最高的 942 精通倍率，相比之下攻击倍率仅仅只有 252 。精通倍率占比之大，远远高于艾尔海森和纳西妲。故把赛索斯攻击权重降低至 30 ，精通权重提高至 100 。
=> 更新艾尔海森、赛索斯、克洛琳德评分权重

resources/meta-gs/artifact/artis-mark.js, resources/meta-gs/character/妮露/artis.js
妮露在满命条件下，双暴权重更改为100。
更改白术的圣遗物评分标准，充能从75提升至100，精通从75降为50。
=> 添加艾梅莉埃、妮露（自定义-满命）的圣遗物评分标准，更改白术的圣遗物评分标准

apps/character/AvatarWife.js, models/MysApi.js, resources/meta-gs/character/枫原万叶/artis.js
* fix issue #761
* feature: 添加老婆 <details> 可以在已设置了老婆的基础上再进行添加，此前只能重新打一堆名字，~~老婆太多就有点麻烦了~~ </details>
=> 修复万叶默认通用评分标准被自定义通用标准覆盖导致默认标准修改后未生效的问题

resources/meta-gs/artifact/artis-mark.js, resources/meta-sr/character/椒丘/artis.js
①调整玛拉妮的圣遗物评分权重
此前低估了玛拉妮的精通价值。
玛拉妮黑曜秘典套 + 专武，且副词条精通值累计小于 50（估值）的情况下，精通杯的单人期望伤害甚至大于水伤杯。
故将玛拉妮的精通权重，从 75 提高到 85.
②增加椒丘在满命情况下的评分权重
与0命相比，双暴权重从0 提升到 100，攻击权重从 50 提升至 75.
=> 调整玛拉妮和椒丘的圣遗物评分权重

resources/meta-gs/artifact/artis-mark.js, resources/meta-sr/character/椒丘/artis.js
变更椒丘满命条件下的圣遗物评分权重
将元素伤害，从 0 提升至 100（之前遗漏）。
将卡齐娜的防御力权重，从 100 降至 75.
理由：卡齐娜纯防御倍率，天赋里并没有防御力转攻击力等额外转模。之前定义 100 过高。
添加基尼奇的评分权重。
需要特别说明的是，基尼奇的专武，白值非常高，圣遗物攻击副词条的收益比其他角色高，暂定 85 。
=> 添加基尼奇，并变更卡齐娜、椒丘（满命）的圣遗物评分权重 

apps/stat/RoleCombatSummary.js
之前查询是用 `auth=all`，所以会出现 ck 和 uid 对不上的报错，即 10104
应采取 `auth=cookie`
=> Fix: 幻想真境剧诗查询必须使用自身ck

apps/profile/ProfileDetail.js, resources/meta-gs/artifact/artis-mark.js, resources/meta-gs/character/希格雯/artis.js, resources/meta-gs/character/芙宁娜/artis.js
敌人默认等级，从91提高至103（配合世界等级9）。
降低夏沃蕾和闲云的治疗权重（防止分数溢出）。
新增希诺宁的评分权重。
添加希格雯满命情况下的评分权重。
优化芙宁娜满命情况下的评分权重部分的代码。
=> 敌人默认等级调整，部分角色圣遗物评分权重调整

resources/meta-sr/artifact/artis-mark.js
=> Update: 更新星铁角色飞霄、云璃、貊泽评分权重

resources/meta-gs/artifact/artis-mark.js
新增恰斯卡、欧洛伦的圣遗物评分规则。
将阿贝多的防御权重，从 100 下调至 75（天赋里没有额外的防御转模）。
=> 新增恰斯卡、欧洛伦的圣遗物评分规则，修改阿贝多的防御权重。

apps/wiki/CalendarSr.js
在获取listData时，网页api会在pic_list[0].type_list中返回两个列表，目前其中一个是annid为727，无banner，无title，其图像为 https://sdk-webstatic.mihoyo.com/upload/ann/2024/11/11/396a2a2cc8784148d8cc8dfb8629fd4c_6874583538831706317.jpg “在第八日启程 版本概览”，通常在pic_list[0].type_list[1]的位置出现，而另一个（pic_list[0].type_list[0]）是正常的游戏内活动公告。
多次测试后发现从api获取到的两个列表的顺序可能发生互换，从而导致不能读取到活动信息。因此只要两个都读取就不会发生此问题。
=> Update CalendarSr.js 关于有时无法显示游戏内活动的信息

apps/profile/ProfileStat.js, config/system/cfg_system.js, package.json
- 完成从 BWiki 数据源获取数据的逻辑
- 配置中新加用于切换数据源的配置项
- 将 `cheerio` 挪至 `dependencies` （参考 #820 #826 ）
=> `#202407幻想角色列表` 加入 BWiki 数据源

resources/meta-gs/artifact/artis-mark.js
恰斯卡的精通权重，从 0 提升至 30.
茜特菈莉的攻击、双暴权重降低至 30，充能权重提高至 100.
=> 修改恰斯卡、茜特菈莉的圣遗物评分规则

resources/meta-gs/artifact/artis-mark.js, resources/meta-gs/character/茜特菈莉/artis.js
将玛薇卡的精通权重，从 75 提高至 85.
虽然火神融化率不是100%，但是同词条的情况下，精通沙的总伤依然稳稳大于攻击沙。
当茜特菈莉的双暴分大于200时，将茜特菈莉的双暴权重提高至100，攻击权重提高至50。
=> 提高玛薇卡的精通权重；添加茜特菈莉自定义圣遗物权重规则

models/attr/AttrData.js, models/dmg/DmgAttr.js, resources/meta-gs/artifact/artis-mark.js, resources/meta-gs/character/玛薇卡/calc.js, resources/meta-sr/artifact/calc.js
这次更新为了配合火神2命，在伤害计算方面，添加了对基础类数值（攻击、防御、生命）变动的支持。
如有自行编写伤害插件的人，可以像本次更新里的玛薇卡伤害计算那样，在 buff 里添加 **atkBase：200** 即可。
且为了防止后续出现诸如基础防御、基础生命之类的变动，这里也提前对这两者做了支持。
如以后出现基础防御力+200，则在伤害计算 buff 里添加 **defBase** 即可。
因为很多人用 liangshi 插件，这里提一嘴。
在liangshi插件 damage/liangshi-gs/玛薇卡/CalcBuff.js 这个文件里。
它的第 **19** 行代码（如下图所示）里的 **atkBase：200** 原本仅做展示作用。
它的真正起作用的代码是第 **20** 行的代码。
然而 ackPct 这个代表着攻击百分比数值的变量，实际上只包含了武器被动和人物天赋内的部分，并不包含圣遗物主副词条、武器副词条、圣遗物套装效果（常驻）等等。
所以才有此更新。
**安装了 liangshi 插件的人，可以自行在本次 miao-plugin 更新后，到对应 liangshi 文件里把第 20 行的代码删除（和第19行末尾的逗号）。或等待 liangshi 插件自行更新。**
[
](url)
=> 添加玛薇卡伤害计算；添加梦见月瑞希圣遗物评分权重；添加铁道新遗器

resources/meta-gs/character/珐露珊/calc.js, resources/meta-sr/artifact/artis-mark.js
添加阿格莱雅、大黑塔、忘归人、星期日、乱破，共5人的铁道角色圣遗物评分权重。
修正珐露珊伤害计算时的天赋缺失。
=> 添加阿格莱雅等5人的铁道角色圣遗物评分权重，修正珐露珊伤害计算

resources/meta-sr/character/椒丘/calc.js, resources/meta-sr/character/缇宝/calc.js
修正缇宝伤害计算BUG——
1、缇宝终结技——使敌方受到伤害提高。应为易伤区，而不是增伤区。
2、缇宝额外能力应为提高生命数值上限9%，而不是生命倍率。
添加椒丘伤害计算。
=> 【星铁】添加椒丘伤害计算；修正缇宝伤害计算BUG

resources/meta-gs/character/伊安珊/calc.js, resources/meta-sr/character/三月七·巡猎/calc.js, resources/meta-sr/character/貊泽/calc.js
添加三月七巡猎、貊泽伤害计算。
调整伊安珊排名标准，将排名标准从“动能标识攻击力提升”变为“E后Q技能伤害”。
=> 添加三月七巡猎、貊泽伤害计算。调整伊安珊排名标准

apps/wiki/CharTalent.js, models/ProfileDmg.js, models/dmg/DmgCalc.js, resources/meta-gs/character/伊法/calc.js, resources/meta-sr/character/遐蝶/calc.js, resources/meta-sr/character/阿格莱雅/calc.js
补充遐蝶【三次死龙焰息+死龙晦翼总伤害】by 其实雨很好。
修正伊法6命额外秘药弹伤害计算——倍率应为120%而不是160%；
优化阿格莱雅天赋附加伤害计算的代码。
=> 补充遐蝶伤害计算【by 其实雨很好】& 修正伊法6命额外秘药弹伤害计算 

models/Button.js
当角色数量超过10个时，角色按钮会超过5行（每行2个），QQBot最多只支持五行按钮，影响界面美观和用户体验。 本次修改在profileList方法中限制最多只显示10个角色按钮，确保按钮不会超过5行，提升了界面整洁性和可用性。
=> 修复角色按钮过多导致按钮行数过多的问题

apps/profile/ProfileDetail.js, resources/character/profile-detail.html
修复pr（<https://github.com/yoimiya-kokomi/miao-plugin/pull/950>）产生的问题
> https://github.com/yoimiya-kokomi/miao-plugin/issues/968
> 查看面板时在根目录下会生成额外文件
经测试，改完之后忆灵技可以正常显示，且不再在根目录生成文件，看他当时的提交记录，就这俩地方，应该没有其他问题了
=> fix: 修复查看角色面板时会在根目录生成额外文件的问题 fix #968

resources/meta-sr/artifact/artis-mark.js, resources/meta-sr/character/缇宝/calc.js, resources/meta-sr/character/风堇/artis.js, resources/meta-sr/weapon/智识/calc.js
=> 添加赛飞儿、风堇（满命）的圣遗物评分规则；修正光锥【生命当付之一炬】的buff名称【by 其实雨很好】
